-- MySQL Script generated by MySQL Workbench
-- Wed 27 Jul 2016 06:35:50 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema searches
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `searches` ;

-- -----------------------------------------------------
-- Schema searches
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `searches` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `searches` ;

-- -----------------------------------------------------
-- Table `searches`.`searches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `searches`.`searches` ;

CREATE TABLE IF NOT EXISTS `searches`.`searches` (
  `search_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `search_name` VARCHAR(255) NOT NULL COMMENT '',
  `search_url` LONGTEXT NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`search_id`)  COMMENT '');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
